[workspace]
members = []

[package]
name = "tmux"
authors = ["NAKASHIMA, Makoto <makoto.nksm+github@gmail.com>"]
version = "0.0.0"
publish = false
edition = "2018"
autobins = false

[[bin]]
name = "tmux"

[dependencies]
c2rust-bitfields = "0.3"
libc = "0.2"

